### ISSUE TITLE
What role does c play in training？

### ISSUE THREAD

**Issue by Icespellcaster** [chklos/dynamical-learning#1]
As a label, c represents the category of the curve and is a linear transformation of the curve period. If c is not used as input and output in training, will the final result be consistent with the original result?

**Comment by chklos** [comment]
The context c is more than just a label, it is necessary to stabilize the dynamics during testing after learning. If you'd remove it during the whole process of pretraining, learning and testing, then the network output z would look fine during pretraining and learning. However, during testing, z would move away from the target (at least when learning an unseen target).

I hope this answers your question. You can also take a look at the Analysis section of our paper, where we explain the role of c in greater detail.
